# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: LWMusic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    macos_build:
      runs-on: macos-latest

      strategy:
        matrix:
          node-version: [10.x, 15.x]

      steps:
      - uses: actions/checkout@v2
      - name: LWMusic-macOS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run make
      - name: Create artifacts folder
        run: mkdir artifacts
      - name: Copy output to artifacts
        run: cp out/lwmusic-darwin-x64/lwmusic.app artifacts/
        run: cp out/lwmusic-darwin-x64/LICENSE artifacts/
        run: cp out/lwmusic-darwin-x64/LICENSES.chromium.html artifacts/
        run: cp out/lwmusic-darwin-x64/version artifacts/
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: artifacts/*
