# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: LWMusic-linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: LWMusic-linux
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run make
    - name: Create artifacts folder
      run: mkdir artifacts && ls out/make/deb/x64 && ls out/make/rpm/x64
    - name: Copy Output (1/2)
      run: cp out/make/deb/x64/lwmusic-linux-x64-1.0.0.deb artifacts/
    - name: Copy Output (2/2)
      run: cp out/make/rpm/x64/lwmusic-linux-x64-1.0.0.rpm artifacts/
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.job }}
        path: artifacts/*
